import { createFileRoute, Link } from "@tanstack/react-router";
import { useMemo, useState, type ChangeEvent } from "react";
import { ArrowLeft, ArrowRight, Check, ImagePlus, Upload, X } from "lucide-react";
import { motion, AnimatePresence } from "framer-motion";
import { Brand } from "@/components/brand";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { Progress } from "@/components/ui/progress";

export const Route = createFileRoute("/encomenda")({
  head: () => ({ meta: [
    { title: "Monte sua encomenda | La'Belle Ateliê" },
    { name: "description", content: "Conte sua ideia e solicite um orçamento personalizado à La'Belle Ateliê." },
    { property: "og:title", content: "Monte sua encomenda | La'Belle Ateliê" },
    { property: "og:description", content: "Vamos transformar sua ideia em algo especial." },
    { property: "og:type", content: "website" }, { name: "twitter:card", content: "summary_large_image" },
  ] }), component: OrderPage,
});

type FormData = { product:string; theme:string; name:string; age:string; colors:string; message:string; notes:string; quantity:string; eventDate:string; city:string; pickupDate:string };
const empty:FormData={product:"",theme:"",name:"",age:"",colors:"",message:"",notes:"",quantity:"",eventDate:"",city:"",pickupDate:""};
const products=["Laços","Papelaria","Chaveiros","Centros de Mesa","Arranjos","Lembrancinhas","Kit de Festa","Outro"];
const examples=["Safari","Princesas","Futebol","Borboletas","Jardim","Ursinho","Casamento","Batizado","Outro"];

function OrderPage(){
 const [step,setStep]=useState(1); const [form,setForm]=useState(empty); const [preview,setPreview]=useState<string>();
 const set=(key:keyof FormData,value:string)=>setForm(v=>({...v,[key]:value}));
 const handleFile=(e:ChangeEvent<HTMLInputElement>)=>{const file=e.target.files?.[0]; if(!file)return; if(preview)URL.revokeObjectURL(preview); setPreview(URL.createObjectURL(file));};
 const message=useMemo(()=>`Olá! Vim pelo site da La'Belle Ateliê 🎀\n\nGostaria de solicitar um orçamento:\n\nProduto: ${form.product || "Não informado"}\nTema: ${form.theme || "Não informado"}\nNome: ${form.name || "Não informado"}\nIdade: ${form.age || "Não informada"}\nQuantidade: ${form.quantity || "Não informada"}\nData do evento: ${form.eventDate || "Não informada"}\nCores: ${form.colors || "Não informadas"}\n\nObservações:\n${form.notes || form.message || "Nenhuma"}\n\nGostaria de saber o valor e disponibilidade.`,[form]);
 const canNext=step===1?!!form.product:step===2?!!form.theme:step===4?!!form.quantity:step===5?!!form.eventDate:true;
 return <div className="min-h-screen bg-background"><header className="border-b border-border bg-paper"><div className="atelier-container grid h-[74px] grid-cols-[1fr_auto_1fr] items-center"><Link to="/" className="flex items-center gap-2 text-xs font-semibold text-muted-foreground hover:text-foreground"><ArrowLeft className="size-4"/><span className="hidden sm:inline">Voltar ao catálogo</span></Link><Brand/><span/></div></header>
 <main className="atelier-container py-10 lg:py-16"><div className="mx-auto max-w-4xl text-center"><span className="text-[.65rem] font-bold tracking-[.3em] text-gold-dark">ENCOMENDA PERSONALIZADA</span><h1 className="mt-3 text-5xl font-semibold sm:text-6xl">Monte sua encomenda</h1><p className="mx-auto mt-3 max-w-xl text-sm leading-6 text-muted-foreground">Conte para nós o que você está imaginando. Vamos transformar sua ideia em algo especial.</p></div>
 <div className="mx-auto mt-10 max-w-4xl"><div className="mb-8 flex items-center gap-4"><span className="shrink-0 text-xs font-bold text-gold-dark">ETAPA {String(step).padStart(2,"0")} DE 07</span><Progress value={(step/7)*100}/></div>
 <div className="min-h-[440px] rounded-[18px] border border-border bg-card p-5 soft-shadow sm:p-9"><AnimatePresence mode="wait"><motion.div key={step} initial={{opacity:0,x:16}} animate={{opacity:1,x:0}} exit={{opacity:0,x:-16}} transition={{duration:.22}}>
 {step===1&&<Step title="O que você deseja personalizar?" subtitle="Escolha uma opção para começar."><div className="grid grid-cols-2 gap-3 sm:grid-cols-4">{products.map(p=><button type="button" key={p} onClick={()=>set("product",p)} className={`relative min-h-28 rounded-[12px] border p-4 font-display text-xl transition ${form.product===p?"border-primary bg-secondary text-gold-dark":"border-border bg-paper hover:border-primary/60"}`}>{form.product===p&&<Check className="absolute right-3 top-3 size-4"/>}{p}</button>)}</div></Step>}
 {step===2&&<Step title="Qual será o tema?" subtitle="Escreva o tema ou selecione uma sugestão."><Input value={form.theme} onChange={e=>set("theme",e.target.value)} placeholder="Ex.: Jardim encantado" className="h-14 rounded-[10px] bg-paper px-4" autoFocus/><div className="mt-5 flex flex-wrap gap-2">{examples.map(x=><button type="button" key={x} onClick={()=>set("theme",x)} className="rounded-full border border-border bg-secondary px-4 py-2 text-xs transition hover:border-primary">{x}</button>)}</div></Step>}
 {step===3&&<Step title="Vamos personalizar" subtitle="Preencha apenas o que fizer sentido para sua encomenda."><div className="grid gap-5 sm:grid-cols-2"><Field label="Nome da pessoa"><Input value={form.name} onChange={e=>set("name",e.target.value)}/></Field><Field label="Idade"><Input value={form.age} onChange={e=>set("age",e.target.value)}/></Field><Field label="Cores desejadas"><Input value={form.colors} onChange={e=>set("colors",e.target.value)} placeholder="Ex.: rosé, creme e dourado"/></Field><Field label="Mensagem ou frase"><Input value={form.message} onChange={e=>set("message",e.target.value)}/></Field><Field label="Observações" wide><Textarea value={form.notes} onChange={e=>set("notes",e.target.value)} className="min-h-28"/></Field></div></Step>}
 {step===4&&<Step title="Qual é a quantidade desejada?" subtitle="Uma estimativa já nos ajuda a preparar seu orçamento."><div className="mx-auto max-w-xs"><Input type="number" min="1" value={form.quantity} onChange={e=>set("quantity",e.target.value)} placeholder="Ex.: 30" className="h-16 text-center text-xl" autoFocus/></div></Step>}
 {step===5&&<Step title="Conte sobre o evento" subtitle="Assim conseguimos avaliar prazo e disponibilidade."><div className="grid gap-5 sm:grid-cols-2"><Field label="Data do evento"><Input type="date" value={form.eventDate} onChange={e=>set("eventDate",e.target.value)}/></Field><Field label="Cidade"><Input value={form.city} onChange={e=>set("city",e.target.value)} placeholder="Vicentina - MS"/></Field><Field label="Data desejada para retirada" wide><Input type="date" value={form.pickupDate} onChange={e=>set("pickupDate",e.target.value)}/></Field></div></Step>}
 {step===6&&<Step title="Envie uma foto de referência" subtitle="Pode ser uma inspiração da internet, uma foto do tema ou uma ideia que você gostou."><label className="relative flex min-h-64 cursor-pointer flex-col items-center justify-center overflow-hidden rounded-[14px] border border-dashed border-primary bg-secondary/45 p-6 text-center transition hover:bg-secondary">{preview?<><img src={preview} alt="Prévia da referência" className="absolute inset-0 h-full w-full object-contain bg-paper"/><span className="absolute right-3 top-3 z-10 grid size-8 place-items-center rounded-full bg-brown-dark text-primary-foreground"><X className="size-4"/></span></>:<><div className="grid size-14 place-items-center rounded-full bg-paper text-gold-dark"><ImagePlus/></div><strong className="mt-4 text-sm">Clique para selecionar uma imagem</strong><span className="mt-1 text-xs text-muted-foreground">JPG, PNG ou WEBP</span></>}<input type="file" accept="image/*" onChange={handleFile} className="sr-only"/></label></Step>}
 {step===7&&<Step title="Sua encomenda" subtitle="Confira os dados antes de abrir a conversa no WhatsApp."><div className="grid gap-8 lg:grid-cols-[1fr_280px]"><dl className="grid grid-cols-2 gap-x-6">{[["Produto",form.product],["Tema",form.theme],["Nome",form.name],["Idade",form.age],["Quantidade",form.quantity],["Data",form.eventDate],["Cores",form.colors],["Cidade",form.city]].map(([k,v])=><div key={k} className="border-b border-border py-3"><dt className="text-[.62rem] font-bold uppercase tracking-widest text-gold-dark">{k}</dt><dd className="mt-1 text-sm">{v||"—"}</dd></div>)}<div className="col-span-2 py-3"><dt className="text-[.62rem] font-bold uppercase tracking-widest text-gold-dark">Observações</dt><dd className="mt-1 text-sm leading-6">{form.notes||"—"}</dd></div></dl><div className="rounded-[12px] bg-secondary p-6"><Upload className="size-6 text-gold-dark"/><p className="mt-4 text-sm leading-6 text-muted-foreground">A imagem de referência ficará apenas na prévia. Você poderá enviá-la na conversa do WhatsApp.</p></div></div><Button asChild variant="whatsapp" size="atelier" className="mt-8 w-full"><a href={`https://wa.me/5567998517483?text=${encodeURIComponent(message)}`} target="_blank" rel="noreferrer">Enviar para a La'Belle pelo WhatsApp <ArrowRight/></a></Button></Step>}
 </motion.div></AnimatePresence></div>
 <div className="mt-6 grid grid-cols-2 gap-3"><Button variant="atelierOutline" size="atelier" onClick={()=>setStep(s=>Math.max(1,s-1))} disabled={step===1}><ArrowLeft/> Voltar</Button>{step<7&&<Button variant="atelier" size="atelier" onClick={()=>setStep(s=>Math.min(7,s+1))} disabled={!canNext}>Continuar <ArrowRight/></Button>}</div></div></main></div>;
}

function Step({title,subtitle,children}:{title:string;subtitle:string;children:React.ReactNode}){return <div><div className="mb-8 text-center"><h2 className="text-4xl font-semibold">{title}</h2><p className="mt-2 text-sm text-muted-foreground">{subtitle}</p></div>{children}</div>}
function Field({label,children,wide=false}:{label:string;children:React.ReactNode;wide?:boolean}){return <label className={wide?"sm:col-span-2":""}><span className="mb-2 block text-xs font-bold text-brown">{label}</span>{children}</label>}